version: '3.5'
services:
  dify_workflow_openapi:
    container_name: dify_workflow_openapi
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    ports:
      - "3012:3012"
    restart: always
    environment: 
      - DIFY_API_URL=http://kb.itcg.cn/v1
      - BOT_TYPE=Workflow